version: 1
disable_existing_loggers: False

formatters:
  default:
    format: "[%(asctime)s] %(levelname)s in %(name)s: %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: default
    stream: ext://sys.stdout

loggers:
  uvicorn:
    level: INFO
    handlers: [console]
    propagate: False

  uvicorn.error:
    level: ERROR
    handlers: [console]
    propagate: False

  uvicorn.access:
    level: INFO
    handlers: [console]
    propagate: False

root:
  level: DEBUG
  handlers: [console]
